### PR TITLE
adding cybermancers to the list of creative coders

### PR DESCRIPTION
**Pull request by mwmwmw**

### CODE REVIEW

**Comment by j0hnm4r5** [comment]
Thanks for the submission!

I don't think this falls squarely into the Creative Technology bucket, but creative coding is obviously adjacent and this might benefit from a section for that.

I'm going to hold off on merging this in until we get more entries to put in that new section. If you have any more, please feel free to add them here.

**Comment by mwmwmw** [comment]
Hey, no worries

Just to clarify, do you feel the creative technology needs to have a strong physical component to qualify?

**Comment by j0hnm4r5** [comment]
I think it does? Or at least some non-digital component.

That's not to say that to be considered a Creative Technologist, every project someone does must be a strict combination of physical and digital components. But the knowledge of how to do both sides of that coin at the organizational level is important.

**Comment by mwmwmw** [comment]
Ok, that makes sense. Related, overlapping disciplines, but not the same. 

We just got out first gallery space project, using haptics and virtual sculptures. But it's a sub for a bigger studio. 

I'm happy to hunt down creative coders and virtual experience creators if you think that would add value to this list.

**Comment by j0hnm4r5** [comment]
Honestly, once you get some images of physical installations on the site, I can totally add it.

I do think adding creative coding would be beneficial though. I do a fair number of interviews at Deeplocal, and a good chunk of people applying for CT roles have mostly video game dev and creative coding experience. So, other people obviously consider that CT, which means we should probably add it).

We're working on a new organization method over in #41 too, so that might help.

**Pull request closed without merging**
